on:
  push:
  pull_request:

jobs:
  call-workflow-in-another-repo:
    permissions:
      actions: read
      contents: read

      # used in the `job-workflow-ref` job to fetch an OIDC token, which allows
      # the run to determine its ref
      id-token: write

      # required to comment on pull requests with the results of the check
      pull-requests: write
      # required to upload the results to GitHub's code scanning service
      security-events: write

    uses: grafana/shared-workflows/.github/workflows/reusable-zizmor.yml@iainlane/zizmor-job-workflow-ref

    with:
      fail-severity: never
      runs-on: ubuntu-arm64-small
